apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-backend-monitor
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - val-ns-4
  selector:
    matchLabels:
      app: auth-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http