apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
  labels:
    app: auth-backend 
spec:
  selector:
    app: auth-backend
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
