apiVersion: v1
kind: Service
metadata:
  name: discount-backend-service
  labels:
    app: discount-backend
spec:
  selector:
    app: discount-backend
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  type: ClusterIP
