apiVersion: v1
kind: Service
metadata:
  name: items-service
  labels:
    app: items-service
spec:
  selector:
    app: items
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
